name: Run Scrapers

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-levels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Level 1 scraper
        env:
          CHROME_BIN: ${{ steps.chrome.outputs.chrome-path }}
        run: python level1.py

      - name: Run Level 2 scraper
        env:
          CHROME_BIN: ${{ steps.chrome.outputs.chrome-path }}
        run: python level2.py

      - name: Run Level 3 scraper
        env:
          CHROME_BIN: ${{ steps.chrome.outputs.chrome-path }}
        run: python level3.py
